export const gers = [
  { id: 1, name: "Chae Min A", link: "https://my-ger-shop.vercel.app/", image: "/images/Ger1.png"},
  { id: 2, name: "Kim Hee Joeng", link: "https://hj-shop.vercel.app/", image: "/images/Ger2.png" },
  { id: 3, name: "Jeong Seon Hyung", link: "https://sh-shop-six.vercel.app/", image: "/images/Ger1.png" },
  { id: 4, name: "Park Jae Yong", link: "https://jy-shop.vercel.app/", image: "/images/Ger2.png" },
  { id: 5, name: "은유", link: "https://haliuka.vercel.app/", image: "/images/Ger1.png"},
  { id: 6, name: "하나", link: "https://anarmaa.vercel.app/", image: "/images/Ger2.png" },
  { id: 7, name: "지성", link: "https://anand-six.vercel.app/", image: "/images/Ger1.png" },
  { id: 8, name: "소망", link: "https://khuslen-delta.vercel.app/", image: "/images/Ger2.png" },
  { id: 9, name: "류신", link: "https://orgilsaikhan.vercel.app/", image: "/images/Ger1.png"},
  { id: 10, name: "노을", link: "https://tana-peach.vercel.app/", image: "/images/Ger2.png" },
  { id: 11, name: "미란", link: "https://maral-beryl.vercel.app/", image: "/images/Ger1.png" },
  { id: 12, name: "규리", link: "https://mungundolgion.vercel.app/", image: "/images/Ger2.png" },
  { id: 13, name: "사랑", link: "https://munguu.vercel.app/", image: "/images/Ger1.png"},
  { id: 14, name: "지안", link: "https://namuun-theta.vercel.app/", image: "/images/Ger2.png" },
  { id: 15, name: "평화", link: "https://orgil-ten.vercel.app/", image: "/images/Ger1.png" },
  { id: 16, name: "현우", link: "https://mgerelt.vercel.app/", image: "/images/Ger2.png" },
  { id: 17, name: "민재", link: "https://kimminje.vercel.app/", image: "/images/Ger1.png"},
  { id: 18, name: "태훈", link: "https://tenuuntenger.vercel.app/", image: "/images/Ger2.png" },
  { id: 19, name: "동찬", link: "https://temuujin-kappa.vercel.app/", image: "/images/Ger1.png" },
  { id: 20, name: "하늘", link: "https://uuganbadrakh.vercel.app/", image: "/images/Ger2.png" },
  { id: 21, name: "미소", link: "https://misheel-livid.vercel.app/", image: "/images/Ger1.png"},
  { id: 22, name: "진아", link: "https://amina-delta.vercel.app/", image: "/images/Ger2.png" },
  { id: 23, name: "은달", link: "https://lkhamnorjmaa.vercel.app/", image: "/images/Ger1.png" },
  { id: 24, name: "영원", link: "https://gantulga.vercel.app/", image: "/images/Ger2.png" },
  { id: 25, name: "별이", link: "https://nasannemeh.vercel.app/", image: "/images/Ger1.png"},
  { id: 26, name: "아윤", link: "https://enhzul.vercel.app/", image: "/images/Ger2.png" },
  { id: 27, name: "빛나", link: "https://altjin.vercel.app/", image: "/images/Ger1.png" },
  { id: 28, name: "세라", link: "https://sera-one.vercel.app/", image: "/images/Ger2.png" },
  { id: 29, name: "노현", link: "https://jargl.vercel.app/", image: "/images/Ger1.png"},
];
