export const gers = [
  { id: 1, name: "Chae Min A", link: "https://my-ger-shop.vercel.app/", image: "/images/Ger1.png"},
  { id: 2, name: "Kim Hee Joeng", link: "https://hj-shop.vercel.app/", image: "/images/Ger2.png" },
  { id: 3, name: "Jeong Seon Hyung", link: "https://sh-shop-six.vercel.app/", image: "/images/Ger1.png" },
  { id: 4, name: "Park Jae Yong", link: "https://jy-shop.vercel.app/", image: "/images/Ger2.png" },
  { id: 5, name: "haliuka", link: "https://haliuka.vercel.app/", image: "/images/Ger1.png"},
  { id: 6, name: "anarmaa", link: "https://anarmaa.vercel.app/", image: "/images/Ger2.png" },
  { id: 7, name: "anand", link: "https://anand-six.vercel.app/", image: "/images/Ger1.png" },
  { id: 8, name: "khuslen", link: "https://khuslen-delta.vercel.app/", image: "/images/Ger2.png" },
  { id: 9, name: "orgilsaikhan", link: "https://orgilsaikhan.vercel.app/", image: "/images/Ger1.png"},
  { id: 10, name: "tana", link: "https://tana-peach.vercel.app/", image: "/images/Ger2.png" },
  { id: 11, name: "maral", link: "https://maral-beryl.vercel.app/", image: "/images/Ger1.png" },
  { id: 12, name: "mungundolgion", link: "https://mungundolgion.vercel.app/", image: "/images/Ger2.png" },
  { id: 13, name: "munguu", link: "https://munguu.vercel.app/", image: "/images/Ger1.png"},
  { id: 14, name: "namuun", link: "https://namuun-theta.vercel.app/", image: "/images/Ger2.png" },
  { id: 15, name: "orgil", link: "https://orgil-ten.vercel.app/", image: "/images/Ger1.png" },
  { id: 16, name: "mgerelt", link: "https://mgerelt.vercel.app/", image: "/images/Ger2.png" },
  { id: 17, name: "kimminje", link: "https://kimminje.vercel.app/", image: "/images/Ger1.png"},
  { id: 18, name: "tenuuntenger", link: "https://tenuuntenger.vercel.app/", image: "/images/Ger2.png" },
  { id: 19, name: "temuujin", link: "https://temuujin-kappa.vercel.app/", image: "/images/Ger1.png" },
  { id: 20, name: "uuganbadrakh", link: "https://uuganbadrakh.vercel.app/", image: "/images/Ger2.png" },
  { id: 21, name: "misheel", link: "https://misheel-livid.vercel.app/", image: "/images/Ger1.png"},
  { id: 22, name: "amina", link: "https://amina-delta.vercel.app/", image: "/images/Ger2.png" },
  { id: 23, name: "lkhamnorjmaa", link: "https://lkhamnorjmaa.vercel.app/", image: "/images/Ger1.png" },
  { id: 24, name: "gantulga", link: "https://gantulga.vercel.app/", image: "/images/Ger2.png" },
  { id: 25, name: "nasannemeh", link: "https://nasannemeh.vercel.app/", image: "/images/Ger1.png"},
  { id: 26, name: "enhzul", link: "https://enhzul.vercel.app/", image: "/images/Ger2.png" },
  { id: 27, name: "altjin", link: "https://altjin.vercel.app/", image: "/images/Ger1.png" },
  { id: 28, name: "sera", link: "https://sera-one.vercel.app/", image: "/images/Ger2.png" },
  { id: 29, name: "jargl", link: "https://jargl.vercel.app/", image: "/images/Ger1.png"},
];
