import { Geist } from "next/font/google";
import "./globals.css";
import Header from "../../shared/layout/Header";
import { Suspense } from 'react';
import GlobalSpinner from "../../shared/ui/Spinner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative mt-4 w-full h-screen items-center flex flex-col">
        <Header/>
        <Suspense fallback={<GlobalSpinner />}>
                {children}
        </Suspense>
      </body>
    </html>
  );
}
